import type { NewsPhoto } from './news';
export const septemberPhotos: Record<string, NewsPhoto> = {
  "fungus": {
    "path": "https://times-abema.ismcdn.jp/mwimgs/5/d/1200w/img_5de26b61d820e45519115e2a61ca99194135659.jpg",
    "alt": "Arte de divulgação de Fungus and Iron, apresentada no anúncio inicial do anime em março de 2026.",
    "caption": "Arte de divulgação de Fungus and Iron, apresentada no anúncio inicial do anime em março de 2026.",
    "creator": "© Ayaka Katayama / Kodansha / produção do anime",
    "sourceUrl": "https://times.abema.tv/en/articles/-/10229819",
    "originalUrl": "https://times-abema.ismcdn.jp/mwimgs/5/d/1200w/img_5de26b61d820e45519115e2a61ca99194135659.jpg",
    "sourceName": "ABEMA Times",
    "license": "Direitos reservados",
    "licenseUrl": "https://times.abema.tv/en/articles/-/10229819",
    "rightsReserved": true,
    "width": 1200,
    "height": 1599
  },
  "mayday": {
    "path": "https://www.apple.com/tv-pr/articles/2026/02/apple-tv-debuts-first-look-image-for-the-highly-anticipated-feature-mayday-starring-ryan-reynolds-and-kenneth-branagh-premiering-globally-on-september-4-2026/images/all-news-images/020326_Apple_TV_debuts_Mayday_news_16_9_regular.jpg.latest_news_og.jpg?1770075185686",
    "alt": "Ryan Reynolds e Kenneth Branagh em imagem de divulgação de Mayday.",
    "caption": "Ryan Reynolds e Kenneth Branagh em imagem de divulgação de Mayday.",
    "creator": "Divulgação / Apple TV; fotógrafo não informado na fonte",
    "sourceUrl": "https://www.apple.com/tv-pr/news/2026/02/apple-tv-debuts-first-look-image-for-the-highly-anticipated-feature-mayday-starring-ryan-reynolds-and-kenneth-branagh-premiering-globally-on-september-4-2026/",
    "originalUrl": "https://www.apple.com/tv-pr/articles/2026/02/apple-tv-debuts-first-look-image-for-the-highly-anticipated-feature-mayday-starring-ryan-reynolds-and-kenneth-branagh-premiering-globally-on-september-4-2026/images/all-news-images/020326_Apple_TV_debuts_Mayday_news_16_9_regular.jpg.latest_news_og.jpg?1770075185686",
    "sourceName": "Apple TV",
    "license": "Direitos reservados",
    "licenseUrl": "https://www.apple.com/tv-pr/news/2026/02/apple-tv-debuts-first-look-image-for-the-highly-anticipated-feature-mayday-starring-ryan-reynolds-and-kenneth-branagh-premiering-globally-on-september-4-2026/",
    "rightsReserved": true,
    "width": 1200,
    "height": 630
  },
  "back-future": {
    "path": "https://images.contentstack.io/v3/assets/blt13adb7e2033fcee5/blt2cedc246dc1f28fb/6918f44e086d047d1b046e47/BackToTheFuture_keyart_desktop_2000x3000.jpg?width=1200",
    "alt": "Cartaz oficial de De Volta para o Futuro, filme de 1985.",
    "caption": "Cartaz oficial de De Volta para o Futuro, filme de 1985.",
    "creator": "Arte de divulgação / Universal Pictures",
    "sourceUrl": "https://www.universalpicturesathome.com/movies/back-to-the-future",
    "originalUrl": "https://images.contentstack.io/v3/assets/blt13adb7e2033fcee5/blt2cedc246dc1f28fb/6918f44e086d047d1b046e47/BackToTheFuture_keyart_desktop_2000x3000.jpg?width=1200",
    "sourceName": "Universal Pictures",
    "license": "Direitos reservados",
    "licenseUrl": "https://www.universalpicturesathome.com/movies/back-to-the-future",
    "rightsReserved": true,
    "width": 1200,
    "height": 1800
  },
  "wolverine": {
    "path": "https://blog.br.playstation.com/tachyon/sites/4/2026/06/0a9171a8853a982c29c551c58e5d855f9d5fe8a6-scaled.jpg",
    "alt": "Imagem oficial de Marvel’s Wolverine divulgada pela PlayStation em junho de 2026.",
    "caption": "Imagem oficial de Marvel’s Wolverine divulgada pela PlayStation em junho de 2026.",
    "creator": "© Marvel / Sony Interactive Entertainment / Insomniac Games",
    "sourceUrl": "https://blog.br.playstation.com/2026/06/02/marvels-wolverine-novos-detalhes-sobre-o-gameplay-e-a-historia-no-state-of-play/",
    "originalUrl": "https://blog.br.playstation.com/tachyon/sites/4/2026/06/0a9171a8853a982c29c551c58e5d855f9d5fe8a6-scaled.jpg",
    "sourceName": "PlayStation Blog",
    "license": "Direitos reservados",
    "licenseUrl": "https://blog.br.playstation.com/2026/06/02/marvels-wolverine-novos-detalhes-sobre-o-gameplay-e-a-historia-no-state-of-play/",
    "rightsReserved": true,
    "width": 2560,
    "height": 1440
  },
  "dune": {
    "path": "https://images.penguinrandomhouse.com/cover/9780441172719",
    "alt": "Capa da edição em inglês de Dune, de Frank Herbert.",
    "caption": "Capa da edição em inglês de Dune, de Frank Herbert.",
    "creator": "Arte da edição / Penguin Random House",
    "sourceUrl": "https://penguinrandomhousesecondaryeducation.com/book/?isbn=9780441172719",
    "originalUrl": "https://images.penguinrandomhouse.com/cover/9780441172719",
    "sourceName": "Penguin Random House",
    "license": "Direitos reservados",
    "licenseUrl": "https://penguinrandomhousesecondaryeducation.com/book/?isbn=9780441172719",
    "rightsReserved": true,
    "width": 251,
    "height": 450
  },
  "rick": {
    "path": "https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
    "alt": "Rick Astley no videoclipe oficial de Never Gonna Give You Up, de 1987.",
    "caption": "Rick Astley no videoclipe oficial de Never Gonna Give You Up, de 1987.",
    "creator": "Reprodução do videoclipe / canal oficial de Rick Astley",
    "sourceUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "originalUrl": "https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
    "sourceName": "Rick Astley",
    "license": "Direitos reservados",
    "licenseUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "rightsReserved": true,
    "width": 480,
    "height": 360
  },
  "cosmos": {
    "path": "https://www.nomanssky.com/media/rqiasomo/spacemisc-10.jpg?v=1dd405b3b15d0f0&width=1920",
    "alt": "Cena de No Man’s Sky divulgada com a atualização Cosmos.",
    "caption": "Cena de No Man’s Sky divulgada com a atualização Cosmos.",
    "creator": "© Hello Games",
    "sourceUrl": "https://www.nomanssky.com/cosmos-update/",
    "originalUrl": "https://www.nomanssky.com/media/rqiasomo/spacemisc-10.jpg?v=1dd405b3b15d0f0&width=1920",
    "sourceName": "Hello Games",
    "license": "Direitos reservados",
    "licenseUrl": "https://www.nomanssky.com/cosmos-update/",
    "rightsReserved": true,
    "width": 1920,
    "height": 1080
  },
  "co-op": {
    "path": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1426210/capsule_616x353.jpg?t=1777395376",
    "alt": "Arte oficial de It Takes Two, um dos jogos desta seleção cooperativa.",
    "caption": "Arte oficial de It Takes Two, um dos jogos desta seleção cooperativa.",
    "creator": "© Electronic Arts / Hazelight",
    "sourceUrl": "https://store.steampowered.com/app/1426210/It_Takes_Two/",
    "originalUrl": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1426210/capsule_616x353.jpg?t=1777395376",
    "sourceName": "EA / Steam",
    "license": "Direitos reservados",
    "licenseUrl": "https://store.steampowered.com/app/1426210/It_Takes_Two/",
    "rightsReserved": true,
    "width": 616,
    "height": 353
  },
  "spider-man": {
    "path": "https://www.sonypictures.com/sites/default/files/title-key-art/spidermanbrandnewday_onesheet_1400x2100_1.jpg",
    "alt": "Cartaz de Spider-Man: Brand New Day divulgado pela Sony Pictures.",
    "caption": "Cartaz de Spider-Man: Brand New Day divulgado pela Sony Pictures.",
    "creator": "© Marvel / Sony Pictures",
    "sourceUrl": "https://www.sonypictures.com/movies/spidermanbrandnewday",
    "originalUrl": "https://www.sonypictures.com/sites/default/files/title-key-art/spidermanbrandnewday_onesheet_1400x2100_1.jpg",
    "sourceName": "Sony Pictures",
    "license": "Direitos reservados",
    "licenseUrl": "https://www.sonypictures.com/movies/spidermanbrandnewday",
    "rightsReserved": true,
    "width": 2000,
    "height": 3000
  },
  "oasis": {
    "path": "https://cdn.abcotvs.com/dip/images/19699036_081826-otrc-oasisdoc-vid.jpg",
    "alt": "Material de divulgação do documentário Oasis: Don’t Look Back in Anger.",
    "caption": "Material de divulgação do documentário Oasis: Don’t Look Back in Anger.",
    "creator": "Divulgação / Disney, Hulu, Magna Studios e Sony Music Vision; fotógrafo não informado",
    "sourceUrl": "https://abc11.com/post/newest-trailer-oasis-dont-look-back-anger-sheds-new-light-gallagher-brothers-reunion-tour/19698657/",
    "originalUrl": "https://cdn.abcotvs.com/dip/images/19699036_081826-otrc-oasisdoc-vid.jpg",
    "sourceName": "ABC11 / divulgação",
    "license": "Direitos reservados",
    "licenseUrl": "https://abc11.com/post/newest-trailer-oasis-dont-look-back-anger-sheds-new-light-gallagher-brothers-reunion-tour/19698657/",
    "rightsReserved": true,
    "width": 1920,
    "height": 1080
  },
  "marieta": {
    "path": "https://s.glbimg.com/og/rg/f/original/2011/03/29/20110301-bg-a-grande-famili.jpg",
    "alt": "Marieta Severo como Nenê em A Grande Família. Foto de arquivo de 2011; não é uma cena de Dom de Iludir.",
    "caption": "Marieta Severo como Nenê em A Grande Família. Foto de arquivo de 2011; não é uma cena de Dom de Iludir.",
    "creator": "TV Globo / Blenda Gomes",
    "sourceUrl": "https://redeglobo.globo.com/novidades/series/noticia/2011/03/grande-familia-nene-assume-chefia-da-associacao-de-moradores.html",
    "originalUrl": "https://s.glbimg.com/og/rg/f/original/2011/03/29/20110301-bg-a-grande-famili.jpg",
    "sourceName": "TV Globo",
    "license": "Direitos reservados",
    "licenseUrl": "https://redeglobo.globo.com/novidades/series/noticia/2011/03/grande-familia-nene-assume-chefia-da-associacao-de-moradores.html",
    "rightsReserved": true,
    "width": 606,
    "height": 404
  },
  "prima": {
    "path": "https://www.universalmusic.ca/wp-content/uploads/sites/1843/2026/09/ALBUMARTWORK-ADELA.jpg",
    "alt": "Capa de PRIMA, álbum de estreia de ADÉLA.",
    "caption": "Capa de PRIMA, álbum de estreia de ADÉLA.",
    "creator": "Arte do álbum / Capitol Records",
    "sourceUrl": "https://www.universalmusic.ca/2026/09/04/adela-releases-debut-album-prima/",
    "originalUrl": "https://www.universalmusic.ca/wp-content/uploads/sites/1843/2026/09/ALBUMARTWORK-ADELA.jpg",
    "sourceName": "Universal Music",
    "license": "Direitos reservados",
    "licenseUrl": "https://www.universalmusic.ca/2026/09/04/adela-releases-debut-album-prima/",
    "rightsReserved": true,
    "width": 726,
    "height": 726
  },
  "gentlemen": {
    "path": "https://dnm.nflximg.net/api/v6/9R7jmI8ri5rJNRlvCsMBDHE5JuQ/AAAABcKrH566rMYPIyT_PTLxYmRQ20UWFvsEwLbGMiaqbSwkt-bnSSTZaxdxZTkXGyrqXMC9ITOF89h-sHbAlNN-rklwkicAKoYEIfIsDJfKfGw.png?r=db6",
    "alt": "Arte de The Gentlemen exibida pela Netflix em seu ranking de TV.",
    "caption": "Arte de The Gentlemen exibida pela Netflix em seu ranking de TV.",
    "creator": "© Netflix",
    "sourceUrl": "https://www.netflix.com/tudum/top10/tv?week=2026-09-13",
    "originalUrl": "https://dnm.nflximg.net/api/v6/9R7jmI8ri5rJNRlvCsMBDHE5JuQ/AAAABcKrH566rMYPIyT_PTLxYmRQ20UWFvsEwLbGMiaqbSwkt-bnSSTZaxdxZTkXGyrqXMC9ITOF89h-sHbAlNN-rklwkicAKoYEIfIsDJfKfGw.png?r=db6",
    "sourceName": "Netflix Tudum",
    "license": "Direitos reservados",
    "licenseUrl": "https://www.netflix.com/tudum/top10/tv?week=2026-09-13",
    "rightsReserved": true,
    "width": 360,
    "height": 153
  },
  "accept": {
    "path": "https://label.napalmrecords.com/images/bands/accept/2026-Accept-band1-photo%20credit%20Robert%20John-web.jpg",
    "alt": "Accept em fotografia de divulgação de 2026.",
    "caption": "Accept em fotografia de divulgação de 2026.",
    "creator": "Robert John / divulgação Accept",
    "sourceUrl": "https://label.napalmrecords.com/accept",
    "originalUrl": "https://label.napalmrecords.com/images/bands/accept/2026-Accept-band1-photo%20credit%20Robert%20John-web.jpg",
    "sourceName": "Napalm Records",
    "license": "Direitos reservados",
    "licenseUrl": "https://label.napalmrecords.com/accept",
    "rightsReserved": true,
    "width": 1000,
    "height": 667
  },
  "liniker": {
    "path": "https://upload.wikimedia.org/wikipedia/commons/0/05/Liniker_%2825758721750%29.jpg",
    "alt": "Liniker em fotografia de arquivo de 2016. A imagem não retrata a gravação de Dom de Iludir.",
    "caption": "Liniker em fotografia de arquivo de 2016. A imagem não retrata a gravação de Dom de Iludir.",
    "creator": "Circuito Fora do Eixo",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Liniker_(25758721750).jpg",
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/0/05/Liniker_%2825758721750%29.jpg",
    "sourceName": "Wikimedia Commons / Flickr",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "rightsReserved": false,
    "width": 1920,
    "height": 1280
  },
  "macross": {
    "path": "https://macross.jp/s3/skiyaki/uploads/link/image/75416/_%CE%94_10%E5%91%A8%E5%B9%B4%E8%A8%98%E5%BF%B5_sRGB_600dpi__20260227_02_macross.jpg",
    "alt": "Ilustração oficial comemorativa dos dez anos de Macross Delta.",
    "caption": "Ilustração oficial comemorativa dos dez anos de Macross Delta.",
    "creator": "Chisato Mita (CAPCOM) / © BIGWEST / Macross Delta Project",
    "sourceUrl": "https://macross.jp/",
    "originalUrl": "https://macross.jp/s3/skiyaki/uploads/link/image/75416/_%CE%94_10%E5%91%A8%E5%B9%B4%E8%A8%98%E5%BF%B5_sRGB_600dpi__20260227_02_macross.jpg",
    "sourceName": "Macross · site oficial",
    "license": "Direitos reservados",
    "licenseUrl": "https://macross.jp/",
    "rightsReserved": true,
    "width": 1200,
    "height": 1688
  },
  "control-assist": {
    "path": "https://blog.playstation.com/tachyon/2028/09/805dc24cfeb0a3136d766b4e28d4d1a269bfde1b.jpg",
    "alt": "Imagem de Control Resonant publicada com a apresentação no PlayStation Blog.",
    "caption": "Imagem de Control Resonant publicada com a apresentação no PlayStation Blog.",
    "creator": "© Remedy Entertainment",
    "sourceUrl": "https://blog.playstation.com/?p=423069",
    "originalUrl": "https://blog.playstation.com/tachyon/2028/09/805dc24cfeb0a3136d766b4e28d4d1a269bfde1b.jpg",
    "sourceName": "PlayStation Blog",
    "license": "Direitos reservados",
    "licenseUrl": "https://blog.playstation.com/?p=423069",
    "rightsReserved": true,
    "width": 1920,
    "height": 1080
  },
  "silent-hill": {
    "path": "https://blog.playstation.com/tachyon/2086/09/fc6106a64932c9dfe6b3d7d6a159d6e823befd62.jpg",
    "alt": "Imagem de Silent Hill: Townfall publicada com a apresentação no PlayStation Blog.",
    "caption": "Imagem de Silent Hill: Townfall publicada com a apresentação no PlayStation Blog.",
    "creator": "© Konami / Annapurna Interactive / Screen Burn",
    "sourceUrl": "https://blog.playstation.com/2026/09/21/silent-hill-townfall-9-ways-first-person-changes-the-iconic-horror-formula/",
    "originalUrl": "https://blog.playstation.com/tachyon/2086/09/fc6106a64932c9dfe6b3d7d6a159d6e823befd62.jpg",
    "sourceName": "PlayStation Blog",
    "license": "Direitos reservados",
    "licenseUrl": "https://blog.playstation.com/2026/09/21/silent-hill-townfall-9-ways-first-person-changes-the-iconic-horror-formula/",
    "rightsReserved": true,
    "width": 1920,
    "height": 1080
  },
  "ace-combat": {
    "path": "https://blog.playstation.com/tachyon/2028/09/238b9403fba493d99193176f4e8617fa982522ab.jpg",
    "alt": "Imagem de Ace Combat 8: Wings of Theve publicada com a apresentação no PlayStation Blog.",
    "caption": "Imagem de Ace Combat 8: Wings of Theve publicada com a apresentação no PlayStation Blog.",
    "creator": "© Bandai Namco",
    "sourceUrl": "https://blog.playstation.com/2026/09/25/how-ace-combat-8-wings-of-theve-uses-first-person-to-tell-a-more-personal-story/",
    "originalUrl": "https://blog.playstation.com/tachyon/2028/09/238b9403fba493d99193176f4e8617fa982522ab.jpg",
    "sourceName": "PlayStation Blog",
    "license": "Direitos reservados",
    "licenseUrl": "https://blog.playstation.com/2026/09/25/how-ace-combat-8-wings-of-theve-uses-first-person-to-tell-a-more-personal-story/",
    "rightsReserved": true,
    "width": 1920,
    "height": 1080
  },
  "control-art": {
    "path": "https://blog.playstation.com/tachyon/2028/09/f17f57630200a7c14c2a49cf3044c4ab36a758fa-scaled.png",
    "alt": "Imagem de Control Resonant publicada com a apresentação no PlayStation Blog.",
    "caption": "Imagem de Control Resonant publicada com a apresentação no PlayStation Blog.",
    "creator": "© Remedy Entertainment",
    "sourceUrl": "https://blog.playstation.com/2026/09/29/how-control-resonants-art-design-and-tech-shaped-its-bosses-paranaturally-twisted-manhattan-and-more/",
    "originalUrl": "https://blog.playstation.com/tachyon/2028/09/f17f57630200a7c14c2a49cf3044c4ab36a758fa-scaled.png",
    "sourceName": "PlayStation Blog",
    "license": "Direitos reservados",
    "licenseUrl": "https://blog.playstation.com/2026/09/29/how-control-resonants-art-design-and-tech-shaped-its-bosses-paranaturally-twisted-manhattan-and-more/",
    "rightsReserved": true,
    "width": 2560,
    "height": 1440
  },
  "mars": {
    "path": "https://d2pn8kiwq2w21t.cloudfront.net/images/e1-PIA26704-sol1762-nav-pano.2e16d0ba.fill-1800x900-c10.jpg",
    "alt": "Panorama de Marte captado pelo Perseverance em fevereiro de 2026. Imagem de arquivo, distinta do panorama da Margin Unit citado no estudo.",
    "caption": "Panorama de Marte captado pelo Perseverance em fevereiro de 2026. Imagem de arquivo, distinta do panorama da Margin Unit citado no estudo.",
    "creator": "NASA / JPL-Caltech",
    "sourceUrl": "https://www.jpl.nasa.gov/news/nasas-perseverance-now-autonomously-pinpoints-its-location-on-mars/",
    "originalUrl": "https://d2pn8kiwq2w21t.cloudfront.net/images/e1-PIA26704-sol1762-nav-pano.2e16d0ba.fill-1800x900-c10.jpg",
    "sourceName": "NASA / JPL",
    "license": "Política de uso de imagens NASA",
    "licenseUrl": "https://www.nasa.gov/nasa-brand-center/images-and-media/",
    "rightsReserved": false,
    "width": 1800,
    "height": 900
  },
  "doom": {
    "path": "https://images.contentstack.io/v3/assets/blt13adb7e2033fcee5/blt77f36f86045ef10a/691c865b676634674e73c2eb/Doom_Rated_Poster_2000x3000_uaa.jpg?width=1200",
    "alt": "Cartaz de Doom (2005), um dos filmes desta seleção de adaptações.",
    "caption": "Cartaz de Doom (2005), um dos filmes desta seleção de adaptações.",
    "creator": "Arte de divulgação / Universal Pictures",
    "sourceUrl": "https://www.universalpicturesathome.com/movies/doom",
    "originalUrl": "https://images.contentstack.io/v3/assets/blt13adb7e2033fcee5/blt77f36f86045ef10a/691c865b676634674e73c2eb/Doom_Rated_Poster_2000x3000_uaa.jpg?width=1200",
    "sourceName": "Universal Pictures",
    "license": "Direitos reservados",
    "licenseUrl": "https://www.universalpicturesathome.com/movies/doom",
    "rightsReserved": true,
    "width": 1200,
    "height": 1800
  },
  "luma": {
    "path": "https://blog.playstation.com/tachyon/2026/09/a1029db8785595ae1e6a1a0b5bf08ca33dd21525.jpg",
    "alt": "Imagem de Luma Island publicada no anúncio da versão para PS5.",
    "caption": "Imagem de Luma Island publicada no anúncio da versão para PS5.",
    "creator": "© Feel Free Games",
    "sourceUrl": "https://blog.playstation.com/2026/09/24/luma-island-is-coming-to-ps5",
    "originalUrl": "https://blog.playstation.com/tachyon/2026/09/a1029db8785595ae1e6a1a0b5bf08ca33dd21525.jpg",
    "sourceName": "PlayStation Blog",
    "license": "Direitos reservados",
    "licenseUrl": "https://blog.playstation.com/2026/09/24/luma-island-is-coming-to-ps5",
    "rightsReserved": true,
    "width": 1920,
    "height": 1080
  },
  "redfall": {
    "path": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1294810/header.jpg?t=1750785261",
    "alt": "Arte oficial de Redfall, um dos jogos citados na lista de lançamentos.",
    "caption": "Arte oficial de Redfall, um dos jogos citados na lista de lançamentos.",
    "creator": "© Bethesda Softworks / Arkane Studios",
    "sourceUrl": "https://store.steampowered.com/app/1294810/Redfall/",
    "originalUrl": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1294810/header.jpg?t=1750785261",
    "sourceName": "Bethesda / Steam",
    "license": "Direitos reservados",
    "licenseUrl": "https://store.steampowered.com/app/1294810/Redfall/",
    "rightsReserved": true,
    "width": 460,
    "height": 215
  },
  "madonna": {
    "path": "https://www.madonna.com/cdn/shop/articles/16092026_de7931e0-cf02-46fc-a9ad-2a563a6d2ce7.jpg?v=1789588038",
    "alt": "Madonna em imagem publicada com o anúncio da abertura do VMA 2026.",
    "caption": "Madonna em imagem publicada com o anúncio da abertura do VMA 2026.",
    "creator": "Divulgação / Madonna; fotógrafo não informado no anúncio",
    "sourceUrl": "https://www.madonna.com/blogs/news/madonna-to-open-the-2026-video-music-awards",
    "originalUrl": "https://www.madonna.com/cdn/shop/articles/16092026_de7931e0-cf02-46fc-a9ad-2a563a6d2ce7.jpg?v=1789588038",
    "sourceName": "Madonna · site oficial",
    "license": "Direitos reservados",
    "licenseUrl": "https://www.madonna.com/blogs/news/madonna-to-open-the-2026-video-music-awards",
    "rightsReserved": true,
    "width": 1400,
    "height": 750
  },
  "prada": {
    "path": "https://www.prada.com/content/dam/pradanux/pradasphere/2027/fashion_shows/ss27-womenswear/look-2/001.jpg",
    "alt": "Imagem da coleção feminina Prada primavera/verão 2027.",
    "caption": "Imagem da coleção feminina Prada primavera/verão 2027.",
    "creator": "Divulgação / Prada; fotógrafo não informado nesta página",
    "sourceUrl": "https://www.prada.com/au/en/pradasphere/fashion-shows/2027/ss-womenswear.html",
    "originalUrl": "https://www.prada.com/content/dam/pradanux/pradasphere/2027/fashion_shows/ss27-womenswear/look-2/001.jpg",
    "sourceName": "Prada",
    "license": "Direitos reservados",
    "licenseUrl": "https://www.prada.com/au/en/pradasphere/fashion-shows/2027/ss-womenswear.html",
    "rightsReserved": true,
    "width": 1600,
    "height": 2400
  },
  "jojo": {
    "path": "https://eiken-anime.jp/wp-content/uploads/2026/09/20261004_9099_1.jpg",
    "width": 640,
    "height": 360,
    "alt": "Cena de Sazae-san em material oficial da Eiken.",
    "caption": "Cena de Sazae-san, em divulgação do próximo programa publicada em setembro. Imagem ilustrativa; não corresponde à semana de medição da audiência.",
    "creator": "© Museu Machiko Hasegawa / Eiken",
    "sourceName": "Sazae-san · portal oficial",
    "sourceUrl": "https://eiken-anime.jp/sazaesan/",
    "originalUrl": "https://eiken-anime.jp/wp-content/uploads/2026/09/20261004_9099_1.jpg",
    "license": "Direitos reservados",
    "licenseUrl": "https://eiken-anime.jp/sazaesan/",
    "rightsReserved": true
  }
};
