import type { NewsItem, NewsSource } from './news';
import { septemberPhotos } from './september-media';

const fernando = 'Fernando Valerious';
const ruby = 'Ruby Dias';
const adailton = 'Adailton Jr.';
const source = (name: string, url: string, date?: string): NewsSource => ({ name, url, date });
type Entry = Omit<NewsItem, 'historicalDate' | 'publishedAt'> & { day: number; media: string };
const entries: Entry[] = [
  {
    day: 3, media: 'fungus', slug: 'fungus-and-iron-anime-visual-equipe', category: 'animes-hqs', byline: adailton, kind: 'news',
    title: 'Fungus and Iron revela equipe do anime e coloca a rebeldia no meio dos cogumelos',
    excerpt: 'Adaptação do mangá de Ayaka Katayama ganha novo visual, direção de Keitaro Motonaga e animação do Yokohama Animation Lab.',
    context: 'Informações anunciadas em 3 de setembro de 2026. O anúncio consultado não confirma uma data de estreia.',
    source: source('Crunchyroll News · anúncio do anime', 'https://www.crunchyroll.com/news/latest/2026/9/3/fungus-and-iron-anime-teaser-visual', '2026-09-03'),
    body: [
      'Se o seu interesse por cogumelos terminava na pizza, Fungus and Iron tem outros planos. A adaptação do mangá de Ayaka Katayama apresentou, em 3 de setembro, um novo visual e os principais responsáveis pela produção. Keitaro Motonaga assume a direção, com animação do Yokohama Animation Lab. A estreia, porém, continua sem data confirmada no anúncio. Dá para comemorar a novidade sem sair inventando contagem regressiva, meu povo.',
      'A história acompanha Dante em uma sociedade controlada por fungos. Um encontro com uma jovem ajuda a colocar em movimento sua resistência ao sistema. O material de divulgação trabalha justamente essa ideia de um soldado que desafia a ordem estabelecida. Não é receita de risoto: é uma distopia em que pensar por conta própria virou assunto perigoso.',
      'O ponto interessante da premissa está na combinação de controle biológico e obediência social. Uma ameaça que ocupa o corpo também interfere na liberdade, e esse encontro permite uma discussão que vai além da aparência estranha do mundo. Na ficção científica, um monstro pode assustar; uma sociedade inteira tratando o absurdo como rotina costuma incomodar ainda mais.',
      'Para quem conheceu a obra no papel, a pergunta agora é como o anime vai construir esse clima. Cor, movimento e som podem destacar a escala do ambiente e tornar a vulnerabilidade dos personagens mais evidente. Isso é uma possibilidade da adaptação, não uma avaliação de episódios que ainda não foram apresentados. Trailer não vem com bola de cristal no pacote.',
      'A notícia concreta é o avanço da produção, com equipe e nova peça visual divulgadas. Até aparecerem informações oficiais sobre lançamento e distribuição, a melhor companhia para a expectativa é acompanhar os comunicados da equipe. Dante pode desafiar as estrelas; a gente, por enquanto, desafia a vontade de acreditar em qualquer calendário que aparece na internet.',
    ],
  },
  {
    day: 4, media: 'mayday', slug: 'mayday-ryan-reynolds-kenneth-branagh-apple', category: 'filmes', byline: fernando, kind: 'news',
    title: 'Mayday estreia com Ryan Reynolds, Kenneth Branagh e uma missão que saiu do controle',
    excerpt: 'Comédia de ação da Apple TV reúne um piloto americano e um ex-agente da KGB em uma aliança improvável durante a Guerra Fria.',
    context: 'Estreia global anunciada pela Apple para 4 de setembro de 2026; comunicado original publicado em 3 de fevereiro.',
    source: source('Apple TV Press · anúncio de Mayday', 'https://www.apple.com/tv-pr/news/2026/02/apple-tv-debuts-first-look-image-for-the-highly-anticipated-feature-mayday-starring-ryan-reynolds-and-kenneth-branagh-premiering-globally-on-september-4-2026/', '2026-02-03'),
    body: [
      'Ryan Reynolds troca o uniforme do mercenário por uma missão de sobrevivência em Mayday, filme com estreia global anunciada para 4 de setembro na Apple TV. Kenneth Branagh divide o protagonismo nessa comédia de ação ambientada na Guerra Fria. A combinação já chama atenção: de um lado, o impulso da piada; do outro, um ator cuja carreira dispensa apresentações. O conflito entre os personagens terá de sustentar o encontro.',
      'Reynolds interpreta Troy Kelly, piloto da Marinha americana enviado a uma operação secreta em território russo. Quando o plano desanda, ele fica atrás das linhas inimigas e encontra Nikolai Ustinov, ex-agente da KGB vivido por Branagh. A sinopse oficial propõe uma aliança improvável entre homens que, em princípio, deveriam desconfiar um do outro. Em filmes assim, a diplomacia costuma chegar depois da primeira confusão.',
      'John Francis Daley e Jonathan Goldstein assinam roteiro, direção e produção. Maria Bakalova, Marcin Dorocinski e David Morse também estão no elenco divulgado. São informações da apresentação da Apple, suficientes para situar a produção sem transformar um anúncio promocional em crítica de cinema.',
      'O atrativo da proposta está no contraste. Uma comédia de parceiros funciona melhor quando a diferença entre eles produz decisões e consequências, em vez de servir apenas de intervalo para uma frase engraçada. O cenário de espionagem amplia essa possibilidade: confiança, idioma e objetivos podem virar obstáculos tão importantes quanto a ameaça externa. É aí que a premissa merece atenção.',
      'Para o público que acompanha Reynolds por Deadpool, vale ajustar a expectativa: este é outro personagem e outro universo. Fã da Marvel não precisa enxergar participação especial em toda porta que abre. Mayday chega como uma história própria, e o anúncio de lançamento oferece um motivo para colocá-la na agenda. A avaliação do filme exige o filme; a estreia, por sua vez, já tem endereço e data.',
    ],
  },
  {
    day: 5, media: 'back-future', slug: 'dez-melhores-filmes-viagem-no-tempo-spn', category: 'filmes', byline: adailton, kind: 'opinion',
    title: '10 filmes de viagem no tempo para bagunçar o relógio sem perder a diversão',
    excerpt: 'Nossa seleção editorial vai de De Volta para o Futuro a Questão de Tempo: paradoxo, ação, romance e gente precisando conversar antes de apertar um botão.',
    context: 'Seleção de opinião editorial de 5 de setembro. A ordem reflete os critérios do SPN: força da ideia, personagens e variedade de abordagens; não é um ranking de audiência.',
    source: source('Universal Pictures · De Volta para o Futuro', 'https://www.universalpicturesathome.com/movies/back-to-the-future'),
    sources: [source('Universal Pictures · De Volta para o Futuro', 'https://www.universalpicturesathome.com/movies/back-to-the-future'), source('Universal Pictures · Questão de Tempo', 'https://www.universalpicturesathome.com/movies/about-time'), source('Rotten Tomatoes · filmes de viagem no tempo', 'https://editorial.rottentomatoes.com/guide/essential-sci-fi-movies-of-all-time/')],
    body: ['Tem filme que pede pipoca. Filme de viagem no tempo pede pipoca, atenção e a humildade de aceitar que talvez você precise desenhar uma seta. A seleção abaixo privilegia histórias que fazem alguma coisa interessante com o tempo: uma aventura divertida, uma escolha dolorosa ou uma pergunta que fica martelando depois dos créditos.', 'A ordem é nossa, não do universo. Também não é competição de precisão científica: a proposta é avaliar como o recurso ajuda a contar uma história. Se alguém voltar ao passado para mudar a lista, ao menos deixe a versão anterior salva.'],
    sections: [
      { title: '1. De Volta para o Futuro (1985)', source: 0, paragraphs: ['Marty McFly vai a 1955 e ameaça o próprio futuro. A ideia ganha força porque o problema é familiar antes de ser científico: conhecer os pais antes de eles virarem seus pais. Para esta lista, é o equilíbrio mais simpático entre aventura e consequência. Reunião de família já dá trabalho sem máquina do tempo.'] },
      { title: '2. O Exterminador do Futuro 2 (1991)', source: 2, paragraphs: ['O futuro envia sua violência ao presente. A escolha aqui privilegia a maneira como ação e responsabilidade caminham juntas: evitar um desastre exige decisões agora. O espetáculo pode ser enorme, mas a pergunta continua próxima. Se o amanhã está em disputa, ficar olhando para o relógio não resolve.'] },
      { title: '3. Os 12 Macacos (1995)', source: 2, paragraphs: ['Uma missão temporal vira uma investigação cheia de incerteza. O filme merece posição alta por fazer da dúvida parte da experiência: informação nem sempre significa entendimento. É uma boa escolha para quem prefere um quebra-cabeça a uma explicação embrulhada para presente. Aqui, até a confiança precisa de comprovante.'] },
      { title: '4. No Limite do Amanhã (2014)', source: 2, paragraphs: ['A repetição de um dia se transforma em aprendizado sob pressão. O recurso interessa porque obriga a aventura a mudar mesmo quando o relógio volta ao início. Na nossa seleção, essa combinação de tentativa, erro e ação vale bastante. É o treinamento mais inconveniente do mundo: faltou o botão de descansar.'] },
      { title: '5. Questão de Tempo (2013)', source: 1, paragraphs: ['O poder de voltar no tempo entra na vida afetiva de um jovem. A escolha valoriza a pergunta sobre o cotidiano: o que merece ser vivido com atenção, mesmo sem poder ser consertado? É romance com uma ideia maior por baixo. Nem toda viagem precisa salvar o planeta; às vezes, precisa melhorar uma conversa.'] },
      { title: '6. Looper (2012)', source: 2, paragraphs: ['Um assassino encontra um problema vindo do próprio futuro. A premissa coloca identidade e consequência no mesmo confronto. Entra pela disposição de tratar o amanhã como uma responsabilidade incômoda, não como um passeio turístico. Se você já evita mensagem do banco, imagine uma cobrança enviada por você mesmo.'] },
      { title: '7. Predestinado (2014)', source: 2, paragraphs: ['Identidade e paradoxos sustentam uma história feita para reorganizar suas certezas. O atrativo está na construção do mistério, razão pela qual esta indicação evita entregar as viradas. Quem gosta de terminar o filme discutindo a lógica encontra aqui bastante assunto. Só não vale fazer apresentação de slides antes de todo mundo assistir.'] },
      { title: '8. Feitiço do Tempo (1993)', source: 2, paragraphs: ['Um homem repete o mesmo dia e precisa mudar por dentro. A comédia encontra no ciclo temporal uma maneira eficiente de discutir convivência. O relógio não avança, mas o personagem pode avançar. Para a lista, isso pesa mais do que uma máquina cheia de luzes. Evolução pessoal, aparentemente, também aceita repetição.'] },
      { title: '9. Donnie Darko (2001)', source: 2, paragraphs: ['Uma opção para quem gosta de estranheza, angústia e interpretação. A relação com o tempo ajuda a criar um mundo em que a normalidade parece sempre prestes a falhar. A indicação vale pela atmosfera de pergunta aberta. Não prometemos resposta confortável; prometemos assunto para o caminho de volta.'] },
      { title: '10. Bill & Ted: Uma Aventura Fantástica (1989)', source: 2, paragraphs: ['A viagem temporal vira uma aventura cômica movida pela amizade. Fecha a seleção por lembrar que uma boa ideia também pode existir sem solenidade. O futuro já costuma ser pesado; a ficção tem direito a uma folga. E estudar história com deslocamento temporal, convenhamos, parece uma vantagem pouco justa na prova.'] },
    ],
  },
  {
    day: 6, media: 'wolverine', slug: 'wolverine-setembro-identidade-logan', category: 'cultura-pop', byline: fernando, kind: 'feature',
    title: 'Wolverine entra na contagem regressiva com uma pergunta: o jogo vai entender Logan?',
    excerpt: 'Com lançamento marcado para 15 de setembro, o mutante da Insomniac aproxima os universos dos quadrinhos e dos games.',
    context: 'Panorama editorial em 6 de setembro, baseado em informações de lançamento e história divulgadas anteriormente pela PlayStation.',
    source: source('PlayStation Brasil · história e gameplay de Wolverine', 'https://blog.br.playstation.com/2026/06/02/marvels-wolverine-novos-detalhes-sobre-o-gameplay-e-a-historia-no-state-of-play/', '2026-06-02'),
    body: ['Marvel’s Wolverine está marcado para chegar ao PlayStation 5 em 15 de setembro. Desenvolvido pela Insomniac Games, o jogo coloca Logan no centro de uma aventura própria. Para quem acompanha o personagem nos quadrinhos, a data importa; a abordagem importa ainda mais. Garras são fáceis de reconhecer. O homem que vive com elas é um trabalho mais exigente.', 'O material da PlayStation apresenta uma história ligada ao passado do personagem e à sua identidade. Isso oferece uma base melhor do que simplesmente medir a quantidade de inimigos derrubados. Wolverine funciona quando sua capacidade de sobreviver entra em conflito com aquilo que precisa suportar. A recuperação do corpo nunca resolveu automaticamente as complicações da cabeça.', 'Como fã da Marvel e da DC, interessa ver um jogo usar os poderes para construir personagem, não apenas para preencher uma barra de habilidade. A violência pode fazer parte de Logan, mas perder o controle tem um significado que precisa existir além da animação. Caso contrário, sobra uma ferramenta afiada e falta uma história para justificar seu uso.', 'A proximidade do lançamento também pede cuidado com a expectativa. Apresentações oficiais mostram a intenção da equipe; o conjunto só pode ser avaliado quando a experiência estiver disponível. Tratar toda imagem promocional como prova de excelência é um atalho tentador, especialmente para quem já tem o personagem na estante. Fandom é afeto, não certificado de qualidade.', 'Em 6 de setembro, o que existe de concreto é a programação anunciada e a proposta apresentada. O jogo tem uma oportunidade clara: fazer a ação carregar o peso de Logan. Se conseguir, a adaptação poderá conversar com o fã antigo e com quem está chegando agora. Até lá, a torcida está autorizada. A nota ainda não.'],
  },
  {
    day: 7, media: 'dune', slug: 'duna-frank-herbert-livro-cultura-pop', category: 'cultura-pop', byline: fernando, kind: 'guide',
    title: 'Antes de outra viagem a Arrakis, Duna merece sair da estante',
    excerpt: 'A agenda cinematográfica recoloca a saga em conversa; o livro de Frank Herbert oferece política, ecologia e uma boa desconfiança de salvadores.',
    context: 'Recomendação literária da edição de 7 de setembro. O novo filme está anunciado para dezembro; este texto discute o romance original, sem antecipar uma crítica da produção.',
    source: source('Penguin Random House · Duna', 'https://penguinrandomhousesecondaryeducation.com/book/?isbn=9780441172719'),
    sources: [source('Penguin Random House · Duna', 'https://penguinrandomhousesecondaryeducation.com/book/?isbn=9780441172719'), source('Warner Bros. · site oficial de Dune: Part Three', 'https://www.dunemovie.com/home/')],
    body: ['Com Dune: Part Three anunciado para dezembro de 2026, Arrakis volta a ocupar espaço na agenda do cinema. A recomendação literária de hoje, porém, começa antes da próxima tela: Duna, de Frank Herbert. O romance que abriu a saga é uma entrada importante para entender por que esse universo continua produzindo adaptações e debates. Não precisa decorar uma enciclopédia para começar; precisa aceitar que o deserto tem mais camadas do que parece.', 'A história acompanha Paul Atreides em um planeta estratégico por causa da especiaria, recurso que estrutura disputas de poder. Famílias, instituições e habitantes locais não enxergam Arrakis do mesmo modo. Esse conflito ajuda a tornar o cenário algo além de uma paisagem exótica. O território tem valor para quem o explora e tem vida para quem mora nele. Confundir as duas coisas é parte do problema.', 'O motivo da indicação está nessa combinação de aventura e disputa de ideias. Duna permite olhar para liderança, tradição, recursos naturais e interesses políticos dentro de uma narrativa de ficção científica. Minha preferência é por obras que deixam perguntas depois da empolgação. Um herói anunciado como resposta para tudo deveria, no mínimo, passar por uma boa entrevista antes de receber as chaves do universo.', 'Para quem chegou pelos filmes, o livro oferece outro ritmo. Nomes e relações se acumulam, e vale ler sem a obrigação de avançar em velocidade de trailer. Não há mérito especial em terminar depressa e esquecer o conflito central. Uma pausa para entender quem quer o quê costuma render mais do que correr até a próxima cena grandiosa.', 'A escolha do SPN é o romance original como ponto de partida. O próximo filme pertence à agenda anunciada; a leitura tem seu próprio caminho e não depende de uma estreia para valer a pena. Entre uma guerra cósmica e outra, Herbert deixa um lembrete útil: poder, ambiente e crença raramente vivem separados. A especiaria move muita coisa. O senso crítico também deveria.'],
  },
  {
    day: 8, media: 'rick', slug: 'rick-astley-never-gonna-give-you-up-nostalgia', category: 'musica', byline: ruby, kind: 'feature',
    title: 'Rick Astley prometeu não desistir — e a internet levou a promessa a sério',
    excerpt: 'Never Gonna Give You Up saiu em 1987 e ganhou outra vida como rickroll. A nostalgia de hoje olha para a canção por trás da pegadinha.',
    context: 'Coluna de nostalgia em 8 de setembro de 2026. A música é de 1987; o texto não anuncia um novo lançamento ou usa um contador de visualizações atual como dado histórico.',
    source: source('Official Charts · histórico de Never Gonna Give You Up', 'https://www.officialcharts.com/songs/rick-astley-never-gonna-give-you-up/'),
    sources: [source('Official Charts · histórico da música', 'https://www.officialcharts.com/songs/rick-astley-never-gonna-give-you-up/'), source('Rick Astley · vídeo oficial', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ')],
    body: ['Você procura uma informação, abre um link e encontra Rick Astley. O rickroll transformou Never Gonna Give You Up em uma das pegadinhas mais reconhecíveis da internet. Mas a coluna de nostalgia de hoje propõe uma pequena reparação: antes de ser a surpresa do navegador, a música já tinha uma vida pop própria. E bastante personalidade para sobreviver ao carinho torto de milhões de cliques.', 'Lançada em 1987, a canção aparece no histórico britânico do Official Charts a partir de agosto daquele ano. O vídeo oficial preserva a apresentação de Astley que a internet depois transformaria em código compartilhado. Não vou fingir que a lembrança nasceu no modem da minha casa. A graça dessa memória é justamente circular entre pessoas que chegaram à mesma música por caminhos muito diferentes.', 'O contraste faz parte do encanto: uma declaração romântica direta ganhou a função de interromper expectativas. A promessa sentimental continua lá, enquanto o contexto muda completamente. É como receber uma carta de amor no envelope de uma conta. Dá vontade de reclamar da entrega; a trilha, pelo menos, veio melhor do que o esperado.', 'Essa segunda vida também mostra como o público interfere no destino de uma obra. Uma música deixa de existir apenas como faixa de um repertório e vira uma linguagem para conversar, brincar e reconhecer outras pessoas. O meme pode parecer pequeno, mas o vínculo que ele cria é real. Às vezes, a cultura pop se mantém viva por uma piada que ninguém precisou explicar duas vezes.', 'A homenagem do SPN é para essa resistência simpática. Vale assistir ao vídeo como música, sem esperar a pegadinha, e depois pensar em como seu significado mudou. Nostalgia não precisa ser competição de quem nasceu antes. Pode ser um encontro entre lembranças diferentes. Rick prometeu permanecer. A internet, com sua habitual delicadeza de um gato derrubando um copo, tratou de ajudar.'],
  },
  {
    day: 9, media: 'cosmos', slug: 'no-mans-sky-cosmos-estacoes-espaciais', category: 'cultura-pop', byline: adailton, kind: 'news',
    title: 'No Man’s Sky Cosmos deixa você administrar uma estação — o universo ganhou síndico',
    excerpt: 'Atualização 7.0 amplia a construção no espaço, apresenta alianças e celebra os dez anos do jogo com uma expedição comemorativa.',
    context: 'Atualização Cosmos divulgada em 9 de setembro de 2026. Recursos descritos no material oficial da Hello Games.',
    source: source('Hello Games · Cosmos Update', 'https://www.nomanssky.com/cosmos-update/', '2026-09-09'),
    body: ['No Man’s Sky recebeu Cosmos, atualização 7.0 que amplia a vida fora dos planetas e permite assumir a direção de uma estação espacial. A Hello Games também apresenta alianças, construção orbital e uma expedição ligada aos dez anos do jogo. Você queria conhecer as estrelas e acabou com um espaço para organizar. Só falta alguém reclamar do barulho da nave depois das dez.', 'A função de diretor permite modificar a estação e sua apresentação. As alianças acrescentam uma camada coletiva à exploração, enquanto a construção orbital abre espaço para bases fora da superfície planetária. O anúncio inclui ainda destroços gigantes para investigar e materiais físicos que podem ser recuperados e transportados. São recursos descritos pela desenvolvedora, não resultado de uma sessão de testes do SPN.', 'A expedição Our Journey Continues propõe uma viagem pela trajetória do jogo. A ideia de transformar a própria história das atualizações em atividade tem um apelo claro: o passado deixa de ser apenas uma lista de versões. Ele passa a fazer parte do que o jogador pode descobrir. Para um universo que vive de explorar, é uma maneira coerente de olhar para trás.', 'O interesse cultural dessa novidade está na mudança de papel. Explorar é uma coisa; ocupar, construir e conviver são outras. Quando o jogo oferece um lugar que pode ser organizado e compartilhado, a aventura ganha histórias que dependem das decisões do público. O destino deixa de ser só um ponto bonito na tela. Vira um espaço com hábitos, planos e, provavelmente, alguém mexendo onde não devia.', 'Cosmos amplia as possibilidades anunciadas sem exigir que a notícia vire propaganda. Quem já acompanha No Man’s Sky pode consultar as notas oficiais para ver o conjunto de mudanças. O resto da gente ganha mais um exemplo de um jogo que constrói sua identidade ao longo do tempo. Dez anos depois, ainda há assunto no céu. E aparentemente também há ata de reunião.'],
  },
];

export const septemberRest: NewsItem[] = entries.map(({ day, media, ...item }) => ({ ...item, historicalDate: `2026-09-${String(day).padStart(2,'0')}`, publishedAt: '2026-10-01T18:44:14.341Z', photo: septemberPhotos[media] }));
