import { requireEditor } from '@/lib/redacao';
import { publishedNews } from '@/lib/published-news';
import { siteUrl } from '@/lib/site';
import { instagramConfigured } from '@/lib/instagram';
import { toggleSocial,cancelSocial } from './actions';
import SocialComposer from './social-composer';
const labels:Record<string,string>={queued:'Na fila',processing:'Em processamento — conferir resultado',published:'Publicada',failed:'Falhou — revisar',uncertain:'Resultado incerto — conferir Instagram',cancelled:'Cancelada'};
const messages:Record<string,string>={conexao:'Configure a autorização da Meta e os segredos privados para ativar.',conta:'Não foi possível confirmar a autorização do @fernando.cspn.',imagem:'Para o envio automático, a foto precisa ter endereço HTTPS público e formato JPEG (.jpg).',duplicada:'Esta matéria já está na fila ou não pôde ser salva. Confira o histórico.',materia:'Esta reportagem não está publicada.',legenda:'A legenda deve ter até 2.200 caracteres.',salvo:'Chamada salva na fila. O envio aguarda ativação e a execução diária.'};
export default async function SocialPage({searchParams}:{searchParams:Promise<{aviso?:string}>}) {
 const {client}=await requireEditor();const params=await searchParams;
 const [settingsResult,queueResult,news]=await Promise.all([client.from('spn_social_settings').select('*').eq('id',true).single(),client.from('spn_social_queue').select('*').order('created_at',{ascending:false}).limit(30),publishedNews()]);
 const enabled=settingsResult.data?.enabled===true,configured=instagramConfigured();
 const articles=news.map(({slug,title,excerpt,byline,photo})=>({slug,title,excerpt,byline,image:photo?.path,imageCredit:photo?.creator}));
 return <><span className="desk-eyebrow">DISTRIBUIÇÃO · SPN NEWS</span><h1>Redes sociais</h1><p className="desk-muted">Prepare chamadas e acompanhe os envios para @fernando.cspn.</p>{params.aviso&&messages[params.aviso]&&<p className="desk-notice" role="status">{messages[params.aviso]}</p>}<section className="desk-card"><h2>Publicação automática no Instagram</h2><span className="desk-state">{enabled?'Ativada':configured?'Pronta para ativar':'Aguardando autorização da Meta'}</span><p className="desk-muted">Uma publicação por dia, a partir das 9h de Brasília. Ao ativar, novas matérias publicadas no site entram na fila automaticamente. A edição antiga de setembro só entra se você selecionar a matéria abaixo. O horário pode variar dentro da janela de execução da hospedagem.</p>{!configured&&<p className="desk-notice">A integração precisa de uma conta profissional autorizada na Meta. Nenhuma senha deve ser enviada pelo chat. As credenciais serão configuradas somente no ambiente privado da hospedagem.</p>}<form action={toggleSocial}><input type="hidden" name="enabled" value={enabled?'false':'true'}/><button className="desk-button" disabled={!configured&&!enabled}>{enabled?'Pausar envios automáticos':'Ativar para novas matérias'}</button></form></section><SocialComposer articles={articles} baseUrl={siteUrl.origin}/><section className="desk-card"><h2>Fila e histórico</h2>{queueResult.error?<p className="desk-notice">Não foi possível carregar a fila. Tente novamente.</p>:!queueResult.data?.length?<p className="desk-muted">Nenhum envio agendado ou realizado.</p>:<div className="desk-table-scroll"><table className="desk-table"><thead><tr><th>Matéria</th><th>Situação</th><th>Ação</th></tr></thead><tbody>{queueResult.data.map(row=><tr key={row.id}><td>{news.find(item=>item.slug===row.slug)?.title??row.slug}<small>{new Date(row.created_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</small></td><td>{labels[row.state]}{row.error&&<small>{row.error}</small>}{row.media_id&&<small>Confirmação da Meta: {row.media_id}</small>}</td><td>{row.state==='queued'&&<form action={cancelSocial}><input type="hidden" name="id" value={row.id}/><button className="desk-button secondary">Cancelar envio</button></form>}</td></tr>)}</tbody></table></div>}</section></>;
}
