'use client';
import { useState } from 'react';
import { queueSocial } from './actions';
import { socialProfiles } from '@/lib/social-profiles';
type Article = { slug: string; title: string; excerpt: string; byline?: string; image?: string; imageCredit?: string };
function captionFor(article: Article, baseUrl: string) { return `${article.title}\n\n${article.excerpt}\n\nLeia no SPN News: ${baseUrl}/noticia/${article.slug}\n\n#SPNNews #CulturaPop`; }
export default function SocialComposer({ articles, baseUrl }: { articles: Article[]; baseUrl: string }) {
  const [slug, setSlug] = useState(articles[0]?.slug ?? '');
  const [caption, setCaption] = useState(articles[0] ? captionFor(articles[0], baseUrl) : '');
  const [notice, setNotice] = useState('');
  const article = articles.find(item => item.slug === slug);
  async function copy(value: string) { try { await navigator.clipboard.writeText(value); setNotice('Copiado. Agora você pode colar no perfil oficial.'); } catch { setNotice('Não foi possível copiar automaticamente. Selecione e copie o texto abaixo.'); } }
  if (!article) return <p className="desk-empty">Publique uma matéria para preparar sua chamada social.</p>;
  const articleUrl = `${baseUrl}/noticia/${article.slug}`;
  return <div className="desk-columns social-workspace"><section className="desk-card"><h2>Preparar publicação</h2><div className="desk-form"><label>Matéria publicada<select value={slug} onChange={event => { const next = articles.find(item => item.slug === event.target.value); if (next) { setSlug(next.slug); setCaption(captionFor(next, baseUrl)); setNotice(''); } }}>{articles.map(item => <option key={item.slug} value={item.slug}>{item.title}</option>)}</select></label><label>Legenda<textarea rows={12} value={caption} onChange={event => setCaption(event.target.value)}/><small>Revise a chamada e adapte ao formato da rede. No Instagram, coloque o link na bio ou no adesivo do story.</small></label><label>Link da reportagem<input readOnly value={articleUrl}/></label></div><div className="desk-actions"><button className="desk-button" onClick={() => copy(caption)}>Copiar legenda</button><button className="desk-button secondary" onClick={() => copy(articleUrl)}>Copiar link</button><a className="desk-button secondary" href={articleUrl} target="_blank" rel="noopener noreferrer">Abrir matéria</a></div><form action={queueSocial} className="desk-actions"><input type="hidden" name="slug" value={article.slug}/><input type="hidden" name="caption" value={caption}/><button className="desk-button">Salvar na fila automática</button></form><p className="desk-muted">A fila é salva, mas só envia com a integração ativa. As edições ficam nesta tela e não são salvas ao sair. Copiar não publica nas redes.</p>{notice && <p className="desk-success" role="status">{notice}</p>}</section><aside><section className="desk-card"><h2>Imagem da matéria</h2>{article.image ? <><div className="social-image" style={{ backgroundImage: `url(${JSON.stringify(article.image)})` }} role="img" aria-label={article.title}/><p className="desk-muted">Crédito: {article.imageCredit || 'Consulte os créditos na reportagem.'}</p><a className="desk-link" href={article.image} target="_blank" rel="noopener noreferrer">Abrir imagem</a><p className="desk-muted">Confira a licença da imagem também para uso nas redes. Esta tela não cria cortes ou artes automaticamente.</p></> : <p className="desk-muted">Esta matéria ainda não possui imagem.</p>}</section><section className="desk-card orange"><h2>Perfis oficiais</h2>{socialProfiles.map(profile => <p key={profile.name}><a className="desk-link" href={profile.url} target="_blank" rel="noopener noreferrer">{profile.name} · {profile.handle} ↗</a></p>)}<span className="desk-state">Perfil oficial</span><p className="desk-muted">Perfil disponível no site. Confira o estado da automação no início desta página.</p></section></aside></div>;
}
