import type { Metadata } from 'next';
import { EditorialContact } from '@/components/editorial-contact';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { articles, getArticle, getCategory } from '@/lib/content';
import { Artwork, Ad, Card, PhotoCredit } from '@/components/editorial';
import { siteUrl } from '@/lib/site';
export function generateStaticParams(){return articles.map(a=>({slug:a.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const a=getArticle(slug);return {title:a?`[Demo] ${a.title}`:'Matéria não encontrada',description:a?.excerpt,alternates:{canonical:`/materia/${slug}`},robots:{index:false,follow:false},openGraph:{type:'article',title:a?`[DEMONSTRAÇÃO] ${a.title}`:undefined,description:a?.excerpt}}}
export default async function ArticlePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=getArticle(slug);if(!a)notFound();const c=getCategory(a.category)!;const schema={'@context':'https://schema.org','@type':'NewsArticle',headline:`[DEMONSTRAÇÃO — FICTÍCIO] ${a.title}`,description:`Conteúdo demonstrativo, não é notícia atual. ${a.excerpt}`,datePublished:a.publishedAt,dateModified:a.publishedAt,author:{'@type':'Organization',name:'Redação SPN — demonstração'},publisher:{'@type':'Organization',name:'SPN News',logo:{'@type':'ImageObject',url:new URL('/icon.svg',siteUrl).href}},mainEntityOfPage:new URL(`/materia/${a.slug}`,siteUrl).href,image:[new URL('/og.svg',siteUrl).href],articleSection:c.name,inLanguage:'pt-BR',isAccessibleForFree:true};return <main id="conteudo" className="wrap page-space"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\u003c')}}/><div className="breadcrumbs"><Link href="/">Início</Link> / <Link href={`/categoria/${c.slug}`}>{c.name}</Link> / Matéria demonstrativa</div><article><header className="article-heading"><span className="eyebrow">{c.name} · DEMONSTRAÇÃO</span><h1>{a.title}</h1><p>{a.excerpt}</p><div className="byline"><strong>Redação SPN · Autor demonstrativo</strong><span><time dateTime={a.publishedAt}>01 de janeiro de 2026</time> · Data de exemplo · {a.minutes} min de leitura</span></div></header><div className="article-art"><Artwork art={a.art} large/></div><PhotoCredit art={a.art}/><div className="article-layout"><div className="article-body"><aside className="demo-notice"><strong>Você está lendo um exemplo.</strong><p>Esta matéria é fictícia e serve para avaliar o portal. Não é uma notícia atual, nem uma recomendação comercial.</p></aside>{a.body.map((p,i)=><div key={i}>{i===1&&<h2>A cultura pop merece uma boa conversa</h2>}{i===3&&<h2>O jeito SPN de contar histórias</h2>}<p>{p}</p></div>)}<EditorialContact title={a.title} path={'/materia/' + a.slug}/><div className="article-end">▶ FIM DA TRANSMISSÃO. A CONVERSA CONTINUA.</div><Link className="button" href={`/categoria/${c.slug}`}>Mais de {c.name} →</Link></div><aside className="article-sidebar"><Ad small/><div className="sidebar-note"><span className="eyebrow">NOSSA FREQUÊNCIA</span><h3>Curiosidade em primeiro lugar.</h3><p>Fontes, contexto e transparência serão parte de cada publicação real.</p><Link href="/sobre#transparencia">Conheça a proposta →</Link></div></aside></div></article><section className="feed"><div className="section-heading"><h2>Continue no play<span className="orange-dot">.</span></h2></div><div className="card-grid">{articles.filter(x=>x.slug!==slug).slice(0,3).map(x=><Card key={x.slug} article={x}/>)}</div></section></main>}

