import Link from 'next/link';
import {getDrafts,requireEditor,stateLabels} from '@/lib/redacao';
import {getEditor} from '../../../../editorial-config/editors';
import {getBotPlan} from '../../../../editorial-config/bot-plan';
export default async function Dashboard(){
 const drafts=await getDrafts(),{client}=await requireEditor(),plan=getBotPlan();
 const{data:slot}=await client.from('spn_schedule').select('*').eq('day',Number(plan.date.slice(-2))).maybeSingle();
 const {data:publications}=await client.from('spn_publications').select('slug').eq('withdrawn',false);
 const stats=[['Rascunhos',drafts.filter(d=>d.state==='draft').length,'Histórias em preparação'],['Em revisão',drafts.filter(d=>d.state==='in_review').length,'Texto, fontes e imagem'],['Aprovadas',drafts.filter(d=>d.state==='approved').length,'Prontas para entrar no ar'],['Publicadas',publications?.length??0,'Com edição no site']];
 return <><div className="desk-intro"><div><span className="desk-eyebrow">SEU DIA NA REDAÇÃO</span><h1>Vamos dar o próximo play<span className="desk-orange">.</span></h1><p className="desk-muted">Uma boa pauta, fontes conferidas e o jeito SPN de contar.</p></div><span className="desk-state">{plan.date.split('-').reverse().join('/')} · Brasília</span></div><div className="desk-stats">{stats.map(([label,count,note])=><div className="desk-stat" key={label}><span>{label}</span><strong>{count}</strong><small>{note}</small></div>)}</div><div className="desk-columns"><section className="desk-card"><div className="desk-card-header"><h2>Na mesa da redação</h2><Link className="desk-link" href="/admin/materias">Ver todas →</Link></div>{drafts.slice(0,5).map((d,i)=><Link href={'/admin/materias/'+d.id} className="desk-task" key={d.id}><span className="desk-task-number">{String(i+1).padStart(2,'0')}</span><div><h3>{d.content.title}</h3><p>{d.content.byline} · <span className={'desk-state '+d.state}>{stateLabels[d.state]}</span></p></div></Link>)}{!drafts.length&&<p className="desk-empty">A mesa está livre. Crie sua primeira matéria.</p>}</section><div><section className="desk-card orange"><span className="desk-eyebrow">PAUTA DO DIA</span><h2 style={{marginTop:14}}>{slot?.subject??'Dia sem pauta definida'}</h2><p className="desk-muted">{slot?getEditor(slot.editor_id)?.name+' · '+slot.article_count+' publicação(ões)':'Defina a pauta no calendário interno.'}</p><Link className="desk-button" href="/admin/materias/nova">Preparar matéria →</Link></section><section className="desk-card"><span className="desk-eyebrow">FLUXO EDITORIAL</span><h2 style={{marginTop:14}}>Primeiro contexto.<br/>Depois, play.</h2><p className="desk-muted">Salve o rascunho, envie para revisão e aprove. A publicação só acontece quando você clicar em publicar.</p><Link className="desk-link" href="/admin/automacao">Configuração da automação →</Link></section></div></div></>;
}
