import type { Metadata } from 'next';
import { DailyNews } from '@/components/news';
import Link from 'next/link';
import { ArrowRight, Flame, Play, Youtube, CheckCircle2, Clapperboard, MonitorPlay, Gamepad2, Headphones, Star, Sparkles, Orbit, List, BarChart3 } from 'lucide-react';
import { articles, categories } from '@/lib/content';
import { videoDemos } from '@/lib/programming';
import { Artwork, CategoryTag, FeatureCard, Ad, Mascot, PhotoCredit } from '@/components/editorial';
import { GiroPanel, WatchFinder, ReleaseCalendar } from '@/components/home-widgets';
export const metadata:Metadata={alternates:{canonical:'/'}};
const categoryIcons=[Clapperboard,MonitorPlay,Gamepad2,Headphones,Star,Sparkles,Orbit];
const descriptions=['Histórias e conversas sobre cinema','Maratonas, episódios e universos','Exploração, jogos e próxima fase','Álbuns, playlists e muito mais','Bastidores do mundo pop','Animação, mangá e quadrinhos','Tendências, memória e curiosidades'];
export default function Home(){
 const hero=articles[0];
 return <main id="conteudo" className="home-page"><div className="wrap"><DailyNews/><p className="demo-section-label">A seguir: exemplos de layout e conteúdo fictício, identificados como demonstração.</p>
 <section className="hot-strip" aria-label="Tendências demonstrativas"><strong><Flame fill="currentColor"/>TÁ PEGANDO FOGO!<span>DEMO</span></strong>{[articles[0],articles[2],articles[3],articles[5],articles[4]].map((a,i)=><Link key={a.slug} href={'/materia/'+a.slug}><b>{i+1}</b><span>{['Cinema em outro universo','A cidade vira playground','Um lado B para ouvir','Por trás dos holofotes','Histórias fora dos quadros'][i]}</span></Link>)}</section>
 <section className="hero-grid" aria-label="Destaques demonstrativos"><div className="hero-feature"><article className="hero-main"><Artwork art="cinema" large/><div className="hero-shade"/><span className="hero-disclosure">DEMONSTRAÇÃO · IMAGEM FICTÍCIA</span><div className="hero-content"><CategoryTag slug="filmes"/><h1><Link href={'/materia/'+hero.slug}>{hero.title}</Link><span>UMA BOA HISTÓRIA NÃO TEM LIMITES.</span></h1><p>{hero.excerpt} O play é só o começo da conversa.</p><Link className="yellow-button" href={'/materia/'+hero.slug}>LEIA A MATÉRIA <ArrowRight size={20}/></Link></div></article><PhotoCredit art="cinema"/></div>
 <div className="hero-side">{articles.slice(1,4).map(a=><div className="side-item" key={a.slug}><Link href={'/materia/'+a.slug} className="side-story"><Artwork art={a.art}/><div className="side-content"><CategoryTag slug={a.category}/><h2>{a.title}</h2><p>{a.excerpt}</p></div><span className="side-demo">DEMO</span></Link><PhotoCredit art={a.art}/></div>)}</div></section>
 <div className="newsroom-grid"><GiroPanel/><section className="videos-panel white-panel"><div className="panel-heading"><h2><Youtube fill="currentColor"/>Vídeos em destaque</h2><Link href="/videos">VER TODOS →</Link></div><Link href={'/videos?video='+videoDemos[0].slug} className="video-cover video-lead"><Artwork art="cinema"/><span className="video-demo">ROTEIRO DEMONSTRATIVO</span><div className="video-copy">HISTÓRIAS<br/>QUE FAZEM<br/><em>A GENTE VIAJAR</em></div><span className="video-play"><Play fill="white" size={26}/></span><span className="video-bottom">SPN TV · PRÉVIA DE CONCEITO</span></Link><PhotoCredit art="cinema"/><div className="video-mini-grid">{videoDemos.slice(1).map(v=><div key={v.slug}><Link href={'/videos?video='+v.slug} className="video-cover"><Artwork art={v.art}/><h3>{v.title}</h3><span className="mini-video-demo">ROTEIRO DEMO</span></Link><PhotoCredit art={v.art}/></div>)}</div></section>
 <aside className="robot-panel"><div className="robot-heading"><Mascot/><h2>O ROBÔ<br/>DA REDAÇÃO<br/><span>ESTÁ GANHANDO FORMA</span></h2></div><div className="robot-checklist">{['Organizar fontes verificadas','Apoiar resumo e tradução','Preparar pacotes sociais','Enviar para revisão humana'].map(t=><p key={t}><CheckCircle2 fill="#33c40b" stroke="white" size={22}/>{t}</p>)}<span>FUNÇÕES PLANEJADAS · AINDA NÃO ATIVAS</span></div><div className="robot-note">Automação com contexto.<br/><strong>Publicação com revisão.</strong><Link href="/admin">CONHEÇA OS BASTIDORES →</Link></div></aside></div>
 <section className="editoria-section"><div className="section-heading"><h2><Flame fill="currentColor"/>Escolha sua editoria</h2><Link href="/busca">EXPLORAR TUDO →</Link></div><div className="editoria-grid">{categories.map((c,i)=>{const Icon=categoryIcons[i];return <Link href={'/categoria/'+c.slug} className="editoria-tile" key={c.slug}><Icon fill={c.slug==='famosos'?'currentColor':'none'}/><h3>{c.slug==='series-streaming'?'Séries':c.name}</h3><p>{descriptions[i]}</p></Link>})}<Link href="/listas" className="editoria-tile"><List/><h3>Listas</h3><p>Seleções, coleções e boas conversas</p></Link></div></section>
 <section className="featured-section"><div className="section-heading"><h2><Clapperboard fill="currentColor"/>Destaques das editorias</h2><Link href="/busca">VER TODOS →</Link></div><div className="featured-grid">{[articles[7],articles[1],articles[2],articles[3],articles[5]].map(a=><FeatureCard key={a.slug} article={a}/>)}</div></section>
 <div className="bottom-grid"><WatchFinder/><ReleaseCalendar/><section className="popular-panel white-panel"><div className="panel-heading"><h2><BarChart3 fill="currentColor"/>Mais lidas da semana</h2></div><span className="ranking-disclosure">RANKING DEMONSTRATIVO · SEM DADOS REAIS</span><ol>{articles.slice(0,5).map(a=><li key={a.slug}><Link href={'/materia/'+a.slug}>{a.title}</Link></li>)}</ol></section></div>
 <Ad/><section className="affiliate"><span className="eyebrow">AFILIADOS · DEMONSTRAÇÃO</span><h2>O seu universo também pode virar coleção.</h2><p>Espaço reservado para recomendações comerciais. Nenhuma oferta ou link de compra está ativo. Futuras comissões serão identificadas junto a cada link.</p><Link href="/sobre#publicidade">Como funcionará <ArrowRight size={16}/></Link></section>
 </div></main>;
}
