import {requireEditor} from '@/lib/redacao';
import {getBotPlan} from '../../../../../editorial-config/bot-plan';
import {getEditorialMonth} from '../../../../../editorial-config/editorial-calendar';
import {editors,getEditor} from '../../../../../editorial-config/editors';
import {saveSlot} from '../actions';
export default async function Calendar({searchParams}:{searchParams:Promise<{mes?:string;salvo?:string}>}){
 const{client}=await requireEditor(),plan=getBotPlan(),p=await searchParams;
 const month=/^20\d{2}-(0[1-9]|1[0-2])$/.test(p.mes??'')?p.mes!:plan.date.slice(0,7),[year,m]=month.split('-').map(Number),days=getEditorialMonth(year,m);
 const{data:slots,error}=await client.from('spn_schedule').select('*').order('day');if(error)throw new Error('Não foi possível carregar o calendário.');
 return <><span className="desk-eyebrow">CONFIGURAÇÃO INTERNA · TODO MÊS</span><h1>Calendário da redação.</h1><p className="desk-muted">A programação se repete nos dias existentes de cada mês. Alterar uma pauta muda a configuração recorrente. Dias sem pauta não geram publicação.</p><form className="desk-filter"><input type="month" name="mes" aria-label="Mês" defaultValue={month}/><button className="desk-button">Ver mês</button></form>{p.salvo&&<p className="desk-toast">Pauta recorrente atualizada.</p>}<div className="desk-calendar">{days.map(({date})=>{const day=Number(date.slice(-2)),slot=slots?.find(s=>s.day===day);return <section key={date} className={'desk-card '+(date===plan.date?'today':'')}><span className="desk-calendar-day">{String(day).padStart(2,'0')}</span><h3>{slot?.subject??'Sem pauta definida'}</h3><p className="desk-muted">{slot?getEditor(slot.editor_id)?.name+' · '+slot.article_count+' publicação(ões)':'Nenhuma publicação programada'}</p><details><summary>Configurar este dia</summary><form action={saveSlot} className="desk-form"><input type="hidden" name="day" value={day}/><label>Assunto<textarea name="subject" required minLength={5} maxLength={1000} rows={3} defaultValue={slot?.subject}/></label><label>Editor<select name="editorId" defaultValue={slot?.editor_id??editors[0].id}>{editors.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></label><label>Formato<select name="kind" defaultValue={slot?.kind??'news'}><option value="news">Notícia</option><option value="guide">Guia</option><option value="feature">Cultura & contexto</option><option value="opinion">Opinião / lista</option><option value="data">Dados</option></select></label><label>Quantidade<input name="count" type="number" min={1} max={10} defaultValue={slot?.article_count??1} required/></label><button className="desk-button">Salvar programação</button></form></details></section>;})}</div></>;
}
